// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#pragma once

#include <memory>
#include <mutex>

#include "arrow/flight/type_fwd.h"
#include "arrow/flight/types.h"
#include "arrow/ipc/options.h"
#include "arrow/type_fwd.h"

namespace arrow::flight {

/// \defgroup flight-async Async Flight Types
/// Common types used for asynchronous Flight APIs.
/// @{

/// \brief Non-templated state for an async RPC.
class ARROW_FLIGHT_EXPORT AsyncListenerBase {
 public:
  AsyncListenerBase();
  virtual ~AsyncListenerBase();

  /// \brief Request cancellation of the RPC.
  ///
  /// The RPC is not cancelled until AsyncListener::OnFinish is called.  Safe to
  /// call from any thread, including while the RPC is finishing.
  void TryCancel();

 protected:
  /// \brief Lock the transport state of this RPC for the duration of a control
  /// call.
  ///
  /// A control call (TryCancel(), AsyncDoGetListener::RequestNext()) must hold
  /// this lock for as long as it uses the state: the transport takes it to clear
  /// the state when the RPC finishes, and only clears it once no control call is
  /// using it, so the state cannot be destroyed under a control call.
  /// \return a unique_lock that guards the transport state for this RPC.
  std::unique_lock<std::mutex> LockRpcState() const;

  /// \brief Transport state for this RPC, null until the call has started and
  /// after it finishes. Only valid while holding the LockRpcState() lock.
  /// \return the transport state for this RPC, or null if the call has not started or has
  /// finished.
  internal::AsyncRpc* rpc_state() const { return rpc_state_.get(); }

 private:
  friend class arrow::flight::internal::ClientTransport;

  /// Guards rpc_state_; see LockRpcState().
  mutable std::mutex rpc_state_mutex_;

  /// Transport-specific state for this RPC.  Transport
  /// implementations may store and retrieve state here via
  /// ClientTransport::SetAsyncRpc and ClientTransport::GetAsyncRpc.
  std::unique_ptr<internal::AsyncRpc> rpc_state_;
};

/// \brief Callbacks for results from async RPCs.
///
/// A single listener may not be used for multiple concurrent RPC
/// calls.  The application MUST hold the listener alive until
/// OnFinish() is called and has finished.
template <typename T>
class ARROW_FLIGHT_EXPORT AsyncListener : public AsyncListenerBase {
 public:
  /// \brief Get the next server result.
  ///
  /// This will never be called concurrently with itself or OnFinish.
  virtual void OnNext(T message) = 0;
  /// \brief Get the final status.
  ///
  /// This will never be called concurrently with itself or OnNext.  If the
  /// error comes from the remote server, then a TransportStatusDetail will be
  /// attached.  Otherwise, the error is generated by the client-side
  /// transport and will not have a TransportStatusDetail.
  virtual void OnFinish(Status status) = 0;
};

/// \brief Callbacks for an asynchronous DoGet read.
///
/// Reuses AsyncListener<FlightStreamChunk>: OnNext() delivers decoded chunks and
/// OnFinish() the terminal status; TryCancel() cancels the whole RPC.  Data is
/// delivered only in response to RequestNext(): there is no eager drain, and at
/// most one request may be outstanding.  With no request outstanding the
/// transport starts no reads, so an application that stops calling RequestNext()
/// bounds what the transport retains: one request reads ahead one FlightData
/// message at a time until a chunk is produced (schema and dictionary messages
/// are read through, and a run of dictionary messages is held until the record
/// batch it belongs to arrives).
///
/// TryCancel() reaches the terminal OnFinish() even with no request outstanding,
/// and so does an expired FlightCallOptions::timeout: the gRPC transport holds
/// the callback stream open for reads started from application threads and
/// releases that hold when the call's deadline expires, so the deadline is
/// reported without another RequestNext().  Normal end of stream is not pushed:
/// it is discovered by the request that finds no more data (as is a server-side
/// terminal status that the transport only learns of when a read completes).
/// Server errors keep their status message and, when the server sent rich
/// trailers, a TransportStatusDetail carrying the exact remote code and
/// details.
class ARROW_FLIGHT_EXPORT AsyncDoGetListener : public AsyncListener<FlightStreamChunk> {
 public:
  /// \brief Request one more chunk.
  ///
  /// Nonblocking: Safe to call from any thread once FlightClient::DoGetAsync()
  /// has been called, including from inside OnSchema()/OnNext().
  /// \return Returns OK if the request was accepted; it is then satisfied by exactly one
  /// OnNext() call (which may carry only Flight app_metadata) or ended by the terminal
  /// OnFinish().
  /// An overlapping request is rejected and does not affect the pending one.
  /// Requests after the RPC finished are rejected.
  /// Rejection never suppresses the final OnFinish() or replaces its status.
  Status RequestNext();
  /// \brief The schema of the stream.
  ///
  /// Called at most once, before the first data-bearing OnNext() and before
  /// OnFinish() of a schema-only stream.  Does not satisfy a pending
  /// RequestNext() (the schema is not data).
  virtual void OnSchema(std::shared_ptr<Schema> schema) {}
};

/// @}

}  // namespace arrow::flight
